# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- script: |
    echo start
    xcodebuild -version
    sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer
    xcode-select -p
    xcodebuild -version
    pwd
    ls -a
    cd scripts/createTOC
    make
    createTOC
    echo end
  displayName: 'Create Table Of Contents'
